### ISSUE TITLE
Game Crash

### ISSUE THREAD

**Issue by Blueye21** [nergizer/mc_issues#1]
**Describe the bug**
The game crashes upon loading, something to do with the block Weathered Sandstone

**To Reproduce**
Start the game

**Expected behavior**
The game to start

**Crash report**
Thread: Render thread
Suspected Mod:
Desertification (desert), Version: 0.23.1
at TRANSFORMER/desert@0.23.1/net.nergizer.desert.block.WeatheredSandstone.m_6724_(WeatheredSandstone.kt:46)
Stacktrace:
at net.minecraft.world.level.block.state.StateHolder.m_61143_(StateHolder.java:98) ~[client-1.20.1-20230612.114412-srg.jar%23166!/:?] {re:classloading,pl:connector_pre_launch:A,re:mixin,pl:connector_pre_launch:A}
at net.nergizer.desert.block.WeatheredSandstone.m_6724_(WeatheredSandstone.kt:46) ~[desert-0.23.1-neo-forge_mapped_srg_1.20.1.jar%23301!/:?] {re:classloading}
at net.minecraft.world.level.block.StairBlock.m_6724_(StairBlock.java:147) ~[client-1.20.1-20230612.114412-srg.jar%23166!/:?] {re:classloading,pl:accesstransformer:B,xf:fml:forge:stairsblock,pl:connector_pre_launch:A}
at net.minecraft.world.level.block.state.BlockBehaviour$BlockStateBase.m_60611_(BlockBehaviour.java:513) ~[client-1.20.1-20230612.114412-srg.jar%23166!/:?] {re:mixin,pl:connector_pre_launch:A,re:classloading,pl:connector_pre_launch:A}
at net.minecraftforge.registries.GameData$BlockCallbacks.onBake(GameData.java:445) ~[forge-1.20.1-47.3.10-universal.jar%23171!/:?] {re:classloading}
at net.minecraftforge.registries.ForgeRegistry.bake(ForgeRegistry.java:562) ~[forge-1.20.1-47.3.10-universal.jar%23171!/:?] {re:mixin,re:classloading,pl:mixin:APP:connectormod.mixins.json:registries.ForgeRegistryMixin from mod connectormod,pl:mixin:APP:connectormod.mixins.json:registries.ClientForgeRegistryMixin from mod connectormod,pl:mixin:A}
at net.minecraftforge.registries.GameData.lambda$freezeData$9(GameData.java:259) ~[forge-1.20.1-47.3.10-universal.jar%23171!/:?] {re:mixin,re:classloading}
at com.google.common.collect.HashBiMap.forEach(HashBiMap.java:576) ~[guava-31.1-jre.jar%23119!/:?] {re:mixin}
at net.minecraftforge.registries.GameData.freezeData(GameData.java:257) ~[forge-1.20.1-47.3.10-universal.jar%23171!/:?] {re:mixin,re:classloading}

**Environment:**
 - Mod Loader: Forge
 - Mod Version: 0.23.1
 - Minecraft Version: 1.20.1
 - Other Mods: Forgified Fabric API, Sinytra Connector

**Comment by JustaFloatingEye** [comment]
Same here! Disabling weathered sandstone in config does not fix it either.

**Comment by nergizer** [comment]
Thanks for reporting this issue. I may have fixed it in the latest update (0.23.2).
I will check this tomorrow.

**Comment by nergizer** [comment]
I have confirmed that this issue affect versions 0.23.1 and 0.23 and seems to be fixed in 0.23.2. The weathered sandstone config option is just for spawning them in the desert. Can you confirm the new version works ?

**Comment by Blueye21** [comment]
0.23.2 works

**Comment by nergizer** [comment]
Thanks. Sorry for the trouble
